from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from . import views
from . import client_views
from . import caregiver_views
from . import family_views
from . import provider_views
from . import assessment_views
from . import home_mod_views
from . import move_manage_views
from . import reporting_views
from . import settings_views
from django.contrib.auth import views as auth_views

"""urlpatterns = [
    url(r'^$', auth_views.login, {'template_name': 'login.html'},name='Login'),
    url(r'^register-user$', social_net_views.register_user, name='Register'),
    url(r'^login$', auth_views.login, {'template_name': 'login.html'},name='Login'),
    url(r'^global-stream$', social_net_views.global_stream, name='GlobalStream'),
    url(r'^profile$', social_net_views.profile, name='Profile'),
]
"""
urlpatterns = [
    url(r'^$', auth_views.LoginView.as_view(template_name='production/wecare_login.html'),name='login'),
    url(r'^home$', views.home,name='home'),
    url(r'^login$', auth_views.LoginView.as_view(template_name='production/wecare_login.html'),name='login'),
    url(r'^logout$', views.logout_view,name='logout'),
    url(r'^caregiver_logout$', views.caregiver_logout_view,name='caregiver_logout'),
    url(r'^register',views.register,name='register'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^pwd_activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.pwd_activate, name='pwd_activate'),
    url(r'^forgot_password', views.ForgotPassword.as_view(),name='forgot_password'),
    url(r'^reset_password',views.reset_password,name='reset_password'),
    url(r'^edit_company', views.EditCompany.as_view(), name='edit_company'),
    url(r'^dashboard',views.dashboard,name='dashboard'),
    url(r'^event_log',views.ViewEventLog.as_view(),name='event_log'),
    url(r'^date_filter_dashboard',views.date_filter_dashboard,name='date_filter_dashboard'),
    url(r'^view_active_caregivers',views.ViewActiveCaregivers.as_view(),name='view_active_caregivers'),
    url(r'^view_daily_incidents', views.ViewDailyIncidents.as_view(),name='view_daily_incidents'),
    url(r'^choose_view_client_incidents', client_views.ChooseViewClientIncidents.as_view(),name='choose_view_client_incidents'),
    url(r'^view_incidents_by_client', client_views.ViewIncidentsByClient.as_view(),name='view_incidents_by_client'),
    url(r'^set_tablet_id_session',views.set_tablet_id_session,name='set_tablet_id_session'),
    url(r'^set_caregiver_time_sheet_session', views.set_caregiver_time_sheet_session,name='set_caregiver_time_sheet_session'),
    url(r'^end_caregiver_time_sheet_session', views.end_caregiver_time_sheet_session,name='end_caregiver_time_sheet_session'),
    url(r'^add_care_manager',views.AddCareManager.as_view(),name='add_care_manager'),
    url(r'^activate_tablet_choose_client',client_views.ActivateTabletChooseClient.as_view(),name='activate_tablet_choose_client'),
    url(r'^activate_tablet_client',client_views.ActivateTabletClient.as_view(),name='activate_tablet_client'),
    url(r'^add_client',client_views.AddClient.as_view(),name='add_client'),
    url(r'^edit_choose_client',client_views.EditChooseClient.as_view(),name='edit_choose_client'),
    url(r'^post_family_details',client_views.post_family_details,name='post_family_details'),
    url(r'^post_provider_details',client_views.post_provider_details,name='post_provider_details'),
    url(r'^post_pharmacy_details',client_views.post_pharmacy_details,name='post_pharmacy_details'),
    url(r'^post_payer_details',client_views.post_payer_details,name='post_payer_details'),
    url(r'^edit_client',client_views.EditClient.as_view(),name='edit_client'),
    url(r'^post_criteria',client_views.post_criteria,name='post_criteria'),
    url(r'^post_certification',client_views.post_certification,name='post_certification'),
    url(r'^post_transfer',client_views.post_transfer,name='post_transfer'),
    url(r'^caregiver_post_criteria',caregiver_views.caregiver_post_criteria,name='caregiver_post_criteria'),
    url(r'^caregiver_post_certification',caregiver_views.caregiver_post_certification,name='caregiver_post_certification'),
    url(r'^caregiver_post_transfer',caregiver_views.caregiver_post_transfer,name='caregiver_post_transfer'),
    #url(r'^edit_client/client_email=(?P<client_email>.*)$',client_views.EditClient.as_view(),name='edit_client'),
    url(r'^get_family_with_id',client_views.get_family_with_id,name='get_family_with_id'),
    url(r'^get_provider_with_id',client_views.get_provider_with_id,name='get_provider_with_id'),
    url(r'^get_pharmacy_with_id',client_views.get_pharmacy_with_id,name='get_pharmacy_with_id'),
    url(r'^get_payer_with_id',client_views.get_payer_with_id,name='get_payer_with_id'),
    url(r'^delete_family_member',client_views.delete_family_member,name='delete_family_member'),
    url(r'^delete_provider',client_views.delete_provider,name='delete_provider'),
    url(r'^delete_pharmacy',client_views.delete_pharmacy,name='delete_pharmacy'),
    url(r'^delete_payer',client_views.delete_payer,name='delete_payer'),
    url(r'^find_caregiver',client_views.FindCaregiver.as_view(),name='find_caregiver'),
    url(r'^choose_caregiver/(?P<client_email>\w+)/$', client_views.ChooseCaregiver.as_view(),name='choose_caregiver'),
    url(r'^choose_caregiver', client_views.ChooseCaregiver.as_view(),name='choose_caregiver'),
    url(r'^select_shifts_choose', caregiver_views.SelectShiftsChoose.as_view(),name='select_shifts_choose'),
    url(r'^schedule_shifts', caregiver_views.ScheduleShifts.as_view(),name='schedule_shifts'),
    url(r'^get_schedule_with_id', caregiver_views.get_schedule_with_id,name='get_schedule_with_id'),
    url(r'^edit_schedule_with_id', caregiver_views.edit_schedule_with_id,name='edit_schedule_with_id'),
    url(r'^delete_schedule_with_id', caregiver_views.delete_schedule_with_id,name='delete_schedule_with_id'),
    url(r'^delete_recurring_schedule_with_id', caregiver_views.delete_recurring_schedule_with_id,name='delete_recurring_schedule_with_id'),
    url(r'^get_assigned_clients_with_caregiver_with_id', caregiver_views.get_assigned_clients_with_caregiver_with_id,name='get_assigned_clients_with_caregiver_with_id'),
    url(r'^get_client_with_email', client_views.get_client_with_email,name='get_client_with_email'),
    # new development for family
    url(r'^get_family_with_email', family_views.get_family_with_email,name='get_family_with_email'),
    # new development for family
    url(r'^get_all_client_with_email', client_views.get_all_client_with_email,name='get_all_client_with_email'),
    url(r'^get_sub_categories', client_views.get_sub_categories,name='get_sub_categories'),
    url(r'^get_tasks_from_master', client_views.get_tasks_from_master,name='get_tasks_from_master'),
    url(r'^assign_choose_client', client_views.AssignTasksChooseClient.as_view(),name='assign_choose_client'),
    url(r'^assign_tasks',client_views.AssignTasks.as_view(),name='assign_tasks'),
    url(r'^create_tasks', client_views.CreateTasks.as_view(),name='create_tasks'),
    url(r'^get_task_with_id', client_views.get_task_with_id,name='get_task_with_id'),
    url(r'^edit_task_with_id', client_views.edit_task_with_id,name='edit_task_with_id'),
    url(r'^delete_task_with_id', client_views.delete_task_with_id,name='delete_task_with_id'),
    url(r'^delete_recurring_task_with_id', client_views.delete_recurring_task_with_id,name='delete_recurring_task_with_id'),
    url(r'^add_caregiver',caregiver_views.AddCaregiver.as_view(),name='add_caregiver'),
    url(r'^edit_choose_caregiver', caregiver_views.EditChooseCaregiver.as_view(),name='edit_choose_caregiver'),
    url(r'^choose_view_caregiver_timesheet', caregiver_views.ChooseViewCaregiverTimesheet.as_view(),name='choose_view_caregiver_timesheet'),
    url(r'^view_caregiver_timesheet', caregiver_views.ViewCaregiverTimesheet.as_view(),name='view_caregiver_timesheet'),
    url(r'^export_all_caregiver_timesheets/csv/$', caregiver_views.export_all_caregiver_timesheets, name='export_all_caregiver_timesheets'),
    url(r'^get_caregiver_with_email', caregiver_views.get_caregiver_with_email,name='get_caregiver_with_email'),
    url(r'^edit_caregiver', caregiver_views.EditCaregiver.as_view(),name='edit_caregiver'),
    url(r'^caregiver_dashboard',caregiver_views.CaregiverDashboard.as_view(),name='caregiver_dashboard'),
    url(r'^view_calendar',caregiver_views.ViewCalendar.as_view(),name='view_calendar'),
    url(r'^view_shifts',caregiver_views.ViewShifts.as_view(),name='view_shifts'),
    url(r'^calendar',caregiver_views.calendar,name='calendar'),
    url(r'^family_dashboard',family_views.FamilyDashboard.as_view(),name=
    'family_dashboard'),
    url(r'^provider_dashboard',provider_views.ProviderDashboard.as_view(),name=
    'provider_dashboard'),
    url(r'^assessment_choose_client',assessment_views.AssessmentChooseClient.as_view(),name='assessment_choose_client'),
    url(r'^assessment_tool',assessment_views.AssessmentTool.as_view(),name=
    'assessment_tool'),
    url(r'^post_assessment_status',assessment_views.post_assessment_status,name='post_assessment_status'),
    url(r'^view_alerts',assessment_views.view_alerts,name='view_alerts'),
    #url(r'^contractor_dashboard',home_mod_views.contractor_dashboard,name=
    #'contractor_dashboard'),
    url(r'^view_projects',home_mod_views.view_projects,name='view_projects'),
    #url(r'^view_bids',home_mod_views.view_bids,name='view_bids'),
    url(r'^move_manager_dashboard',move_manage_views.move_manager_dashboard,
    name='move_manager_dashboard'),
    url(r'^view_move_projects',move_manage_views.view_move_projects,
    name='view_move_projects'),
    url(r'^view_move_bids',move_manage_views.view_move_bids,
    name='view_move_bids'),
    url(r'^view_all_caregivers', reporting_views.ViewAllCaregivers.as_view(),name='view_all_caregivers'),
    url(r'^view_all_clients', reporting_views.ViewAllClients.as_view(),name='view_all_clients'),
    url(r'^view_all_care_managers', reporting_views.ViewAllCareManagers.as_view(),name='view_all_care_managers'),
    url(r'^view_clients_without_caregivers', reporting_views.ViewClientsWithoutCaregiver.as_view(),name='view_clients_without_caregivers'),
    url(r'^view_tasks/(?P<task_type>[\w\-]+)/$', reporting_views.ViewTasks.as_view(),name='view_tasks'),
    url(r'^view_tasks/(?P<task_type>[\w\-]+)/(?P<start_date>\d{4}-\d{2}-\d{2})/(?P<end_date>\d{4}-\d{2}-\d{2})/$', reporting_views.ViewTasks.as_view(),name='view_tasks'),
    url(r'^settings/email_settings', settings_views.EmailSettings.as_view(),name='email_settings'),
    url(r'^home_modification/add_home_modification_manager', home_mod_views.AddHomeModManager.as_view(),name='add_home_mod_manager'),
    url(r'^home_modification/edit_choose_home_mod_user',home_mod_views.EditChooseHomeModUser.as_view(),name='edit_choose_home_mod_user'),
    url(r'^home_modification/get_home_mod_with_email', home_mod_views.get_home_mod_with_email,name='get_home_mod_with_email'),
    url(r'^home_modification/edit_home_mod_user', home_mod_views.EditHomeModUser.as_view(),name='edit_home_mod_user'),
    url(r'^home_modification/dashboard', home_mod_views.Dashboard.as_view(), name='contractor_dashboard'),
    url(r'^home_dashboard', views.HomeDashboard.as_view(), name='home_dashboard'),
    url(r'^choose_contractor/(?P<task_id>[0-9a-f-]+)/$', views.ChooseContractorForTask.as_view(), name='choose_contractor'),
    url(r'^choose_contractor/(?P<task_id>[0-9a-f-]+)/(?P<contractor_id>[0-9a-f-]+)/$', views.ChooseContractorForTask.as_view(), name='choose_contractor'),
    url(r'^view_bids/(?P<task_id>[0-9a-f-]+)/$', home_mod_views.ViewBids.as_view(), name='view_bids'),
    url(r'^view_bids', home_mod_views.ViewBids.as_view(), name='view_bids'),
    url(r'^modify_bid', home_mod_views.ModifyBid.as_view(), name="modify_bid"),
    url(r'^accept_bid/(?P<bid_id>[0-9a-f-]+)/$', home_mod_views.AcceptBid.as_view(), name="accept_bid"),
    url(r'^update_projects', home_mod_views.UpdateProjects.as_view(), name='update_projects'),
    url(r'^home_modification/view_project/(?P<home_mod_project_id>[0-9a-f-]+)/$', home_mod_views.ViewProject.as_view(), name="view_project"),
    url(r'^home_modification/view_project_no_edit/(?P<task_id>[0-9a-f-]+)/$', home_mod_views.ViewProjectDisabled.as_view(), name="view_project_disabled"),
    url(r'^home_modification/save_project_budget', home_mod_views.save_project_budget, name="save_project_budget"),
    url(r'^home_modification/save_project_total_amount_spent', home_mod_views.save_project_total_amount_spent, name="save_project_total_amount_spent"),
    url(r'^home_modification/save_project_duration', home_mod_views.save_project_duration, name="save_project_duration"),
    url(r'^home_modification/save_project_progress', home_mod_views.save_progress, name="save_project_progress"),
    url(r'^home_modification/save_project_status', home_mod_views.save_status, name="save_project_status"),
    url(r'^move_management/add_move_manager', move_manage_views.AddMoveManager.as_view(), name='add_move_manager'),
    url(r'^move_management/edit_choose_move_manager',move_manage_views.EditChooseMoveManager.as_view(),name='edit_choose_move_manager'),
    url(r'^move_management/get_move_manager_email', move_manage_views.get_move_manager_with_email,name='get_move_manager_with_email'),
    url(r'^move_management/edit_move_manager', move_manage_views.EditMoveManager.as_view(),name='edit_move_manager'),
    url(r'^move_management/move_manage_wizard', move_manage_views.MoveManageWizard.as_view(),name='move_manage_wizard'),
    url(r'^move_management/choose_move_contractor/(?P<task_id>[0-9a-f-]+)/$', move_manage_views.ChooseMoveContractorForTask.as_view(), name='choose_move_contractor'),
    url(r'^move_management/choose_move_contractor/(?P<task_id>[0-9a-f-]+)/(?P<manager_id>[0-9a-f-]+)/$', move_manage_views.ChooseMoveContractorForTask.as_view(), name='choose_move_contractor'),
    url(r'^move_management/move_inventory/(?P<task_id>[0-9a-f-]+)/$', move_manage_views.MoveInventory.as_view(), name='move_inventory'),
    url(r'^move_management/move_inventory', move_manage_views.MoveInventory.as_view(), name='move_inventory'),
    url(r'^move_management/edit_move_inventory/(?P<inventory_id>[0-9a-f-]+)/$', move_manage_views.EditMoveInventory.as_view(), name='edit_move_inventory'),
    url(r'^move_management/edit_move_inventory', move_manage_views.EditMoveInventory.as_view(), name='edit_move_inventory'),
    url(r'^move_management/move_manager_dashboard', move_manage_views.MoveManagerDashboard.as_view(), name='move_manager_dashboard'),
    url(r'^move_management/view_move_bids/(?P<task_id>[0-9a-f-]+)/$', move_manage_views.ViewMoveBids.as_view(), name='view_move_bids'),
    url(r'^move_management/view_move_bids', move_manage_views.ViewMoveBids.as_view(), name='view_move_bids'),
    url(r'^move_management/accept_move_bid/(?P<bid_id>[0-9a-f-]+)/$', move_manage_views.AcceptMoveBid.as_view(), name="accept_move_bid"),
    url(r'^move_management/update_move_projects', move_manage_views.UpdateMoveProjects.as_view(), name="update_move_projects"),
    url(r'^move_management/view_move_project/(?P<move_project_id>[0-9a-f-]+)/$', move_manage_views.ViewMoveProject.as_view(), name="view_move_project"),
    url(r'^move_management/view_move_project_no_edit/(?P<task_id>[0-9a-f-]+)/$', move_manage_views.ViewMoveProjectDisabled.as_view(), name="view_move_project_disabled"),
    url(r'^move_management/save_move_project_budget', move_manage_views.save_move_project_budget, name="save_move_project_budget"),
    url(r'^move_management/save_move_project_total_amount_spent', move_manage_views.save_move_project_total_amount_spent, name="save_move_project_total_amount_spent"),
    url(r'^move_management/save_move_project_duration', move_manage_views.save_move_project_duration, name="save_move_project_duration"),
    url(r'^move_management/save_move_project_progress', move_manage_views.save_move_progress, name="save_move_project_progress"),
    url(r'^move_management/save_move_project_status', move_manage_views.save_move_status, name="save_move_project_status"),
    url(r'^move_management/delete_move_task/(?P<task_id>[0-9a-f-]+)/$', move_manage_views.DeleteMoveTask.as_view(), name="delete_move_task"),
    url(r'^send_legal_email_incident', client_views.send_legal_email_incident, name="send_legal_email_incident"),
    url(r'^reporting/daily_activity_report/(?P<start_date>\d{4}-\d{2}-\d{2})/(?P<end_date>\d{4}-\d{2}-\d{2})/$', reporting_views.ViewDailyActivityReport.as_view(), name='daily_activity_report'),
    url(r'^reporting/daily_activity_report', reporting_views.ViewDailyActivityReport.as_view(), name='daily_activity_report'),
    url(r'^legal/choose_client_for_legal', client_views.ChooseClientForLegal.as_view(), name='choose_client_for_legal'),
    url(r'^legal/legal_email', client_views.LegalEmail.as_view(), name='legal_email'),
    # # new development for family
    url(r'^family/choose_client_for_legal_mail', family_views.ChooseClientForLegalMail.as_view(), name='choose_client_for_legal_mail'), 
    url(r'^family/legal_email_family', family_views.LegalEmailFamily.as_view(), name='legal_email_family'),
    # # new development for family
    url(r'^caregiver_schedule_dashboard', views.CaregiverScheduleDashboard.as_view(), name='caregiver_schedule_dashboard'),
    url(r'^get_caregiver_schedules_with_uids', views.get_caregiver_schedules_with_uids, name='get_caregiver_schedules_with_uids'),
    url(r'^client_task_dashboard', views.ClientTaskDashboard.as_view(), name='client_task_dashboard'),
    url(r'^get_client_tasks_with_uids', views.get_client_tasks_with_uids, name='get_client_tasks_with_uids'),
    url(r'^billing/invoice', views.Invoice.as_view(), name='invoice'),
    url(r'^billing/choose_client_for_invoice', views.ChooseClientForInvoice.as_view(), name='choose_client_for_invoice'),
    url(r'^manager_choose_client', views.ManagerChooseClient.as_view(), name='manager_choose_client'),
    url(r'^manager_client_dashboard', views.ManagerClientDashboard.as_view(), name='manager_client_dashboard'),
    url(r'^post_template_radio', caregiver_views.post_template_radio, name='post_template_radio'),
    url(r'^vitals_choose_client', provider_views.ChooseClientVitals.as_view(), name='vitals_choose_client'),
    url(r'^reporting/vitals_report', provider_views.VitalsReport.as_view(), name='vitals_report'),
    url(r'^deactivate_choose_client', client_views.ChooseClientForDeactivate.as_view(), name='deactivate_choose_client'),
    url(r'^deactivate_client', client_views.DeactivateClient.as_view(), name='deactivate_client'),
    url(r'^client/end_of_life_choose_client', client_views.ChooseClientEndOfLife.as_view(), name='end_of_life_choose_client'),
    url(r'^client/end_of_life', client_views.ClientEndOfLifeView.as_view(), name='client_end_of_life'),
    url(r'^client/close_end_of_life/(?P<eol_id>[0-9a-f-]+)/$', client_views.close_end_of_life, name='close_end_of_life'),
    url(r'^family/dashboard_client_signoff_all/(?P<client_uid>[0-9a-f-]+)/$', family_views.client_signoff_all, name='client_signoff_all'),
    url(r'^get_daily_tasks_with_schedule_id', caregiver_views.get_daily_tasks_with_schedule_id, name='get_daily_tasks_with_schedule_id'),
    url(r'^move_management/archive_project/(?P<task_id>[0-9a-f-]+)/$', move_manage_views.ArchiveProject.as_view(), name='archive_move_project'),
    url(r'^home_modification/archive_project/(?P<task_id>[0-9a-f-]+)/$', home_mod_views.ArchiveProject.as_view(), name='archive_home_mod_project'),
    url(r'^home_modification/delete_home_mod_task/(?P<task_id>[0-9a-f-]+)/$', home_mod_views.DeleteHomeModTask.as_view(), name="delete_home_mod_task"),



    #Location Capturing process
    url(r'^set_user_lat_long_session',views.set_user_lat_long_session,name='set_user_lat_long_session'),
    url(r'^caregiver_location_map',views.ViewCareGiverLocationLogs.as_view(),name='caregiver_location_map'),
    
    #setting fcm token for FCM
    url(r'^set_user_fcm_token',views.set_user_fcm_token,name='set_user_fcm_token'),
    url(r'^firebase-messaging-sw.js', views.ServiceWorkerView.as_view(), name='service_worker'),
    

    url(r'^send_call_notification', views.send_call_notification, name='send_call_notification'),
    
    url(r'^schedule_free_caregiver',caregiver_views.ScheduleFreeCaregiver.as_view(),name='schedule_free_caregiver'),
    
    

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
