"""
Django settings for mycareportal project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import dj_database_url
import sendgrid as sendgrid_backend

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ylwi3hn#79&v2(%#k&por1szkfssgih4nn)13t4q9v0sz47*eg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.64','mycareportal.herokuapp.com','localhost','www.wecareportal.com','www.wecarehealthportal.com','127.0.0.1']
#'192.168.2.77'

#AWS SETTINGS
AWS_STORAGE_BUCKET_NAME = 'wecare-media'
AWS_ACCESS_KEY_ID = 'AKIAI2SFPXGFAAHZ5XCQ'
AWS_SECRET_ACCESS_KEY = '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'
AWS_S3_FILE_OVERWRITE = False

# Tell django-storages that when coming up with the URL for an item in S3 storage, keep
    # it simple - just use this domain plus the path. (If this isn't set, things get complicated).
    # This controls how the `static` template tag from `staticfiles` gets expanded, if you're using it.
    # We also use it in the next setting.
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME


#SSL - comment out when running locally
#SECURE_SSL_REDIRECT = True

#Email Settings (Sendgrid)
#EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
#SENDGRID_API_KEY = "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"
#SENDGRID_API_KEY = "SG.VqsAk6c6TOCOo1lrrhYqmQ.cDlIins6gkpl_VDaETyT2hNh4gPiOp6Nl6GnVnVIhZ4"

EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = 'dranjanwecare'
EMAIL_HOST_PASSWORD = 'thepianoman2342'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

#Custom - email sending active_caregivers
CAN_SEND_EMAILS = True

# Application definition

INSTALLED_APPS = [
    'mycareportal_app',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mycareportal.urls'
AUTH_USER_MODEL = 'mycareportal_app.User'
#LOGIN_REDIRECT_URL = 'dashboard'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['mycareportal_app/templates',
                'mycareportal_app/email/care_manager/templates',
                'mycareportal_app/email/caregiver/templates',
                'mycareportal_app/email/family/templates',
                'mycareportal_app/email/provider/templates',
                'mycareportal_app/email/client/templates',
                'mycareportal_app/email/user/templates',
                'mycareportal_app/email/admin/templates',
                'mycareportal_app/email/home_mod_manager/templates',
                'mycareportal_app/email/move_manager/templates',
                'mycareportal_app/email/legal/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mycareportal_app.context_processors.add_roles_to_context',
                'mycareportal_app.context_processors.add_current_user_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'mycareportal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'mycareportal',
        'USER': 'mycareportaluser',
        'PASSWORD': 'mycareportal_user_password',
        'HOST': 'localhost',
        'PORT': '',
    }
}'''

'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'ddasri915aj4lm',
        'USER': 'mddvisgxtlykyp',
        'PASSWORD': '7992880265d59c28e691c8cc8973c63543bf40f5001919dd487a8b219c98556a',
        'HOST': 'ec2-23-23-111-171.compute-1.amazonaws.com',
        'PORT': '5432',
    }
}'''

db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "mycareportal_app/static")
]
LOGIN_URL = 'login'
MEDIA_ROOT = os.path.join(BASE_DIR, "mycareportal_app/media")

STATIC_URL = '/static/'
#MEDIA_URL = 'mycareportal_app/media/'

MEDIA_URL = "https://%s/" % AWS_S3_CUSTOM_DOMAIN
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'


# End session on browser close
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
