# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 02:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_code', models.CharField(max_length=100)),
                ('activity_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_code', models.CharField(max_length=100)),
                ('activity_category_code', models.CharField(max_length=100)),
                ('activity_category', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_task', models.CharField(max_length=2000)),
                ('is_default', models.BooleanField(default=False)),
                ('assessment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.AssessmentCategories')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentTaskCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_task', models.CharField(max_length=2000)),
                ('assessment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.AssessmentCategories')),
            ],
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('date_of_birth', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=40)),
                ('secondary_phone_number', models.CharField(max_length=40)),
                ('ssn', models.IntegerField()),
                ('referrer', models.CharField(blank=True, max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('profile_picture', models.ImageField(default='pictures/img.png', upload_to='pictures/profile_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='CareManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=100)),
                ('can_add', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('date_of_birth', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=40)),
                ('secondary_phone_number', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('profile_picture', models.ImageField(default='pictures/img.png', upload_to='pictures/profile_pictures')),
                ('caregiver', models.ManyToManyField(blank=True, to='mycareportal_app.Caregiver')),
            ],
        ),
        migrations.CreateModel(
            name='ClientAssessmentMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=2)),
                ('assessment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.AssessmentCategories')),
                ('assessment_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.AssessmentTask')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('contact_number', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_category_code', models.CharField(max_length=100)),
                ('activity_task', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('profile_picture', models.ImageField(default='pictures/profile_pictures/img.png', upload_to='pictures/profile_pictures')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeModificationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoveManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=40)),
                ('fax_number', models.CharField(max_length=40)),
                ('policy_start_date', models.DateField()),
                ('policy_end_date', models.DateField()),
                ('policy_number', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=40)),
                ('fax_number', models.CharField(max_length=40)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(max_length=100)),
                ('speciality', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=40)),
                ('secondary_phone_number', models.CharField(blank=True, max_length=40)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_task', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('task_type', models.CharField(max_length=100)),
                ('start_time', models.CharField(blank=True, max_length=10)),
                ('end_time', models.CharField(blank=True, max_length=10)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('attachment', models.FileField(blank=True, upload_to='files/tasks')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_task', models.CharField(max_length=300)),
                ('activity_category_code', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_task', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('start_time', models.CharField(blank=True, max_length=10)),
                ('end_time', models.CharField(blank=True, max_length=10)),
                ('pending', models.BooleanField(default=True)),
                ('complete', models.BooleanField(default=False)),
                ('in_progress', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('attachment', models.FileField(blank=True, upload_to='files/tasks')),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CAREMANAGER', 'Care Manager'), ('FAMILYUSER', 'Family Member'), ('PROVIDERUSER', 'Provider User'), ('CAREGIVER', 'Caregiver'), ('HOMEMODUSER', 'Home Modification User'), ('MOVEMANAGER', 'Move Manager')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clientassessmentmap',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company'),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company'),
        ),
        migrations.AddField(
            model_name='client',
            name='family_contacts',
            field=models.ManyToManyField(blank=True, to='mycareportal_app.FamilyContact'),
        ),
        migrations.AddField(
            model_name='client',
            name='payer',
            field=models.ManyToManyField(blank=True, to='mycareportal_app.Payer'),
        ),
        migrations.AddField(
            model_name='client',
            name='pharmacy',
            field=models.ManyToManyField(blank=True, to='mycareportal_app.Pharmacy'),
        ),
        migrations.AddField(
            model_name='client',
            name='provider',
            field=models.ManyToManyField(blank=True, to='mycareportal_app.Provider'),
        ),
        migrations.AddField(
            model_name='caremanager',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company'),
        ),
        migrations.AddField(
            model_name='caremanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company'),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmenttaskcustom',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company'),
        ),
        migrations.AddField(
            model_name='assessmenttask',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
