# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='role',
            field=models.CharField(choices=[('CAREMANAGER', 'Care Manager'), ('FAMILYUSER', 'Family Member'), ('PROVIDERUSER', 'Provider User'), ('CAREGIVER', 'Caregiver'), ('HOMEMODUSER', 'Home Modification User'), ('MOVEMANAGER', 'Move Manager')], max_length=50),
        ),
    ]
