# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0002_auto_20170510_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(default='pictures/img.png', upload_to='pictures/profile_pictures'),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='zip_code',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='client',
            name='caregiver',
        ),
        migrations.AddField(
            model_name='client',
            name='caregiver',
            field=models.ManyToManyField(blank=True, to='mycareportal_app.Caregiver'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='emergency_contacts',
        ),
        migrations.AddField(
            model_name='client',
            name='emergency_contacts',
            field=models.ManyToManyField(blank=True, to='mycareportal_app.ClientContact'),
        ),
        migrations.AlterField(
            model_name='client',
            name='payer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Payer'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='pharmacy',
        ),
        migrations.AddField(
            model_name='client',
            name='pharmacy',
            field=models.ManyToManyField(blank=True, to='mycareportal_app.Pharmacy'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='provider',
        ),
        migrations.AddField(
            model_name='client',
            name='provider',
            field=models.ManyToManyField(blank=True, to='mycareportal_app.Provider'),
        ),
    ]
