# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0002_clienttabletregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttabletregister',
            name='device_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
