# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0003_auto_20170709_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='profile_picture',
            field=models.ImageField(upload_to='pictures/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(upload_to='pictures/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='familycontact',
            name='profile_picture',
            field=models.ImageField(upload_to='pictures/profile_pictures'),
        ),
    ]
