# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0003_auto_20170512_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='payer',
        ),
        migrations.AddField(
            model_name='client',
            name='payer',
            field=models.ManyToManyField(blank=True, to='mycareportal_app.Payer'),
        ),
    ]
