# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0004_auto_20170512_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_code', models.CharField(max_length=100)),
                ('activity_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_code', models.CharField(max_length=100)),
                ('activity_category_code', models.CharField(max_length=100)),
                ('activity_category', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_category_code', models.CharField(max_length=100)),
                ('activity_task', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=300)),
                ('activity_category_code', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
    ]
