# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0004_auto_20170711_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='time_zone',
            field=models.CharField(default='US/Eastern', max_length=50),
            preserve_default=False,
        ),
    ]
