# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0005_activitymaster_activitysubcategory_defaulttasks_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='first_name',
            field=models.CharField(default='Default1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caregiver',
            name='last_name',
            field=models.CharField(default='Default2', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caregiver',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
