# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0005_client_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='ssn',
            field=models.CharField(max_length=20),
        ),
    ]
