# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0006_auto_20170715_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='policy_number',
            field=models.CharField(max_length=40),
        ),
    ]
