# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0007_auto_20170715_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='familycontact',
            name='power_of_attorney',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
