# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0007_auto_20170514_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
