# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0008_auto_20170715_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='familycontact',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
