# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0009_auto_20170715_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=500)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Caregiver')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='email_address',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='task_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.TaskSchedule'),
        ),
    ]
