# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mycareportal_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0010_auto_20170516_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default=mycareportal_app.models.Company, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company'),
        ),
    ]
