# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0011_taskschedule_task_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskschedule',
            name='comment',
        ),
    ]
