# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0011_auto_20170516_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company'),
        ),
    ]
