# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 20:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0012_remove_taskschedule_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='files/tasks')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('task_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.TaskSchedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
