# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0012_auto_20170516_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task',
            new_name='activity_task',
        ),
    ]
