# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0013_auto_20170517_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_task', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('task_type', models.CharField(max_length=100)),
                ('start_time', models.IntegerField(blank=True)),
                ('end_time', models.IntegerField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_task', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('start_time', models.IntegerField(blank=True)),
                ('end_time', models.IntegerField(blank=True)),
                ('complete', models.BooleanField(default=False)),
                ('in_progress', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
    ]
