# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0014_tasklink'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverTimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_timestamp', models.DateTimeField(auto_now_add=True)),
                ('clock_out_timestamp', models.DateTimeField(blank=True, null=True)),
                ('client_timezone', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Caregiver')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
    ]
