# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0015_caregivertimesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregivertimesheet',
            name='time_worked',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caregivertimesheet',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
