# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0015_auto_20170601_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
