# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0016_taskschedule_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskschedule',
            name='end_time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='start_time',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
