# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0016_auto_20170726_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregivertimesheet',
            name='time_worked',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
