# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0017_auto_20170726_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='zip_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
