# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0017_auto_20170602_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskheader',
            name='attachment',
            field=models.FileField(blank=True, upload_to='files/tasks'),
        ),
        migrations.AddField(
            model_name='taskheader',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='taskheader',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='attachment',
            field=models.FileField(blank=True, upload_to='files/tasks'),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
