# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0018_auto_20170603_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcontact',
            name='secondary_phone_number',
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='city',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='profile_picture',
            field=models.ImageField(default='pictures/img.png', upload_to='pictures/profile_pictures'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='state',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='zip_code',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
