# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0019_auto_20170816_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='payer',
            name='address',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='payer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payer',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='payer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='address',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
