# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0019_auto_20170611_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='emergency_contacts',
            new_name='family_contacts',
        ),
    ]
