# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0020_auto_20170819_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='account_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='parent_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company'),
        ),
    ]
