# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0020_auto_20170612_0401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientContact',
            new_name='FamilyContact',
        ),
    ]
