# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 04:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0021_auto_20170612_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='familycontact',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
