# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0021_auto_20170821_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultIncidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.CharField(max_length=150)),
            ],
        ),
    ]
