# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0022_defaultincidents'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
