# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0022_familycontact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familycontact',
            name='profile_picture',
            field=models.ImageField(default='pictures/profile_pictures/img.png', upload_to='pictures/profile_pictures'),
        ),
    ]
