# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 21:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0023_incidentlocations'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_name', models.CharField(max_length=150)),
                ('location_name', models.CharField(max_length=100)),
                ('incident_timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.DefaultIncidents')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.IncidentLocations')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
