# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0024_incidentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.TaskSchedule'),
            preserve_default=False,
        ),
    ]
