# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0024_assessmentcategories_assessmenttaskcustom_assessmenttaskdefault_clientassessmentmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientassessmentmap',
            name='status',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessmenttaskcustom',
            name='assessment_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.AssessmentCategories'),
        ),
        migrations.AlterField(
            model_name='assessmenttaskdefault',
            name='assessment_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.AssessmentCategories'),
        ),
    ]
