# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0025_auto_20170625_2044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssessmentTaskDefault',
            new_name='AssessmentTask',
        ),
    ]
