# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0025_incidentreport_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_Date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Caregiver')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
    ]
