# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0026_auto_20170626_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttask',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientassessmentmap',
            name='assessment_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.AssessmentCategories'),
        ),
        migrations.AlterField(
            model_name='clientassessmentmap',
            name='assessment_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.AssessmentTask'),
        ),
    ]
