# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0026_caregiverschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caregiverschedule',
            old_name='end_Date',
            new_name='end_date',
        ),
    ]
