# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0027_auto_20170626_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttask',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company'),
        ),
    ]
