# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0027_auto_20170901_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCriteriaMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=2)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientMatchCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ClientMatchCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=2000)),
                ('is_default', models.BooleanField(default=False)),
                ('client_match_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.ClientMatchCategory')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
        migrations.AddField(
            model_name='clientcriteriamap',
            name='client_match_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.ClientMatchCategory'),
        ),
        migrations.AddField(
            model_name='clientcriteriamap',
            name='client_match_criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.ClientMatchCriteria'),
        ),
        migrations.AddField(
            model_name='clientcriteriamap',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company'),
        ),
    ]
