# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-02 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0028_auto_20170901_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverCriteriaMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=2)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Caregiver')),
                ('caregiver_match_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.ClientMatchCategory')),
                ('caregiver_match_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.ClientMatchCriteria')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
    ]
