# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0028_assessmenttask_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='caremanager',
            name='can_add',
            field=models.BooleanField(default=True),
        ),
    ]
