# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0029_caremanager_can_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='provider_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='provider',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
