# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-02 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0029_caregivercriteriamap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caregivercriteriamap',
            old_name='caregiver_match_category',
            new_name='client_match_category',
        ),
        migrations.RenameField(
            model_name='caregivercriteriamap',
            old_name='caregiver_match_criteria',
            new_name='client_match_criteria',
        ),
    ]
