# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0030_auto_20170902_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverCertificationMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=2)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Caregiver')),
                ('client_match_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.ClientMatchCategory')),
                ('client_match_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.ClientMatchCriteria')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverTransferMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(verbose_name=((1, 1), (2, 2), (3, 3)))),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client')),
                ('client_match_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.ClientMatchCategory')),
                ('client_match_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.ClientMatchCriteria')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCertificationMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=2)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Caregiver')),
                ('client_match_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.ClientMatchCategory')),
                ('client_match_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.ClientMatchCriteria')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ClientTransferMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(verbose_name=((1, 1), (2, 2), (3, 3)))),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client')),
                ('client_match_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.ClientMatchCategory')),
                ('client_match_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.ClientMatchCriteria')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
    ]
