# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0031_provider_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payer',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='mode',
        ),
    ]
