# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0031_caregivercertificationmap_caregivertransfermap_clientcertificationmap_clienttransfermap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregivertransfermap',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientcertificationmap',
            name='caregiver',
        ),
        migrations.AddField(
            model_name='caregivertransfermap',
            name='caregiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Caregiver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientcertificationmap',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client'),
            preserve_default=False,
        ),
    ]
