# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0032_auto_20170903_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregivertransfermap',
            name='experience',
            field=models.IntegerField(null=True, verbose_name=((1, 1), (2, 2), (3, 3))),
        ),
        migrations.AlterField(
            model_name='clienttransfermap',
            name='experience',
            field=models.IntegerField(null=True, verbose_name=((1, 1), (2, 2), (3, 3))),
        ),
    ]
