# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0032_auto_20170704_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='policy_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payer',
            name='policy_start_date',
            field=models.DateField(),
        ),
    ]
