# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-09 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import mycareportal_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0033_auto_20170903_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='time_zone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='profile_picture',
            field=models.ImageField(upload_to=mycareportal_app.models.get_caregiver_profile_picture_upload_path),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(upload_to=mycareportal_app.models.get_client_profile_picture_upload_path),
        ),
        migrations.AlterField(
            model_name='familycontact',
            name='profile_picture',
            field=models.ImageField(upload_to=mycareportal_app.models.get_family_profile_picture_upload_path),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='attachment',
            field=models.FileField(upload_to=mycareportal_app.models.get_task_attachment_upload_path),
        ),
    ]
