# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0034_auto_20170909_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caregiverschedule',
            old_name='end_date',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='caregiverschedule',
            name='start_date',
        ),
    ]
