# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0035_auto_20171004_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caregiverschedule',
            old_name='data',
            new_name='date',
        ),
    ]
