# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-08 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0036_auto_20171004_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverScheduleHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Caregiver')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
        migrations.AddField(
            model_name='caregiverschedule',
            name='schedule_header',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.CaregiverScheduleHeader'),
        ),
    ]
