# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-08 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0037_auto_20171008_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiverscheduleheader',
            name='date',
        ),
        migrations.AddField(
            model_name='caregiverscheduleheader',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='caregiverscheduleheader',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
