# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0038_auto_20171008_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulttasks',
            name='task_code',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
