# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-09 01:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0039_defaulttasks_task_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcomment',
            name='caregiver',
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
