# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0041_auto_20171220_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_activated',
            field=models.BooleanField(default=False),
        ),
    ]
