# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 19:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0044_auto_20180112_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 1, 17, 19, 20, 12, 513346)),
            preserve_default=False,
        ),
    ]
