# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0046_auto_20180119_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitymaster',
            name='created',
        ),
        migrations.RemoveField(
            model_name='activitysubcategory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='assessmentcategories',
            name='created',
        ),
        migrations.RemoveField(
            model_name='assessmenttask',
            name='created',
        ),
        migrations.RemoveField(
            model_name='clientmatchcategory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='clientmatchcriteria',
            name='created',
        ),
        migrations.RemoveField(
            model_name='defaultincidents',
            name='created',
        ),
        migrations.RemoveField(
            model_name='defaulttasks',
            name='created',
        ),
        migrations.RemoveField(
            model_name='incidentlocations',
            name='created',
        ),
    ]
