# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0047_auto_20180119_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='time_zone',
            field=models.CharField(max_length=50),
        ),
    ]
