# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0048_auto_20180125_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregivertimesheet',
            name='manual_clock_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caregivertimesheet',
            name='reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
