# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0049_auto_20180128_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='referrer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
