# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0051_auto_20180208_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clock_in_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='clock_out_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='incident_emails',
            field=models.BooleanField(default=True),
        ),
    ]
