# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0052_auto_20180218_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregivertimesheet',
            name='adjusted_clock_out_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caregivertimesheet',
            name='adjusted_time_worked',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
