# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import mycareportal_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0053_auto_20180316_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodificationuser',
            name='address',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='homemodificationuser',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homemodificationuser',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='homemodificationuser',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homemodificationuser',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='homemodificationuser',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homemodificationuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homemodificationuser',
            name='phone_number',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='homemodificationuser',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=mycareportal_app.models.get_home_mod_user_profile_picture_upload_path),
        ),
        migrations.AddField(
            model_name='homemodificationuser',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='homemodificationuser',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
