# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import mycareportal_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0054_auto_20180809_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemodificationuser',
            name='address',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='homemodificationuser',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homemodificationuser',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='homemodificationuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homemodificationuser',
            name='gender',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='homemodificationuser',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homemodificationuser',
            name='phone_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='homemodificationuser',
            name='profile_picture',
            field=models.ImageField(upload_to=mycareportal_app.models.get_home_mod_user_profile_picture_upload_path),
        ),
        migrations.AlterField(
            model_name='homemodificationuser',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='homemodificationuser',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
