# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0055_auto_20180809_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModificationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('cost', models.IntegerField(null=True)),
                ('assessment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.AssessmentCategories')),
                ('assigned_contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_contractor', to='mycareportal_app.HomeModificationUser')),
                ('chosen_contractors', models.ManyToManyField(blank=True, to='mycareportal_app.HomeModificationUser')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
    ]
