# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0056_homemodificationtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModTaskBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cost', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.HomeModificationUser')),
            ],
        ),
        migrations.AlterField(
            model_name='homemodificationtask',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='homemodificationtask',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='homemodtaskbid',
            name='home_mod_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.HomeModificationTask'),
        ),
    ]
