# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0057_auto_20181028_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodificationtask',
            name='chosen_bid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.HomeModTaskBid'),
        ),
    ]
