# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0058_homemodificationtask_chosen_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(default='Ongoing', max_length=10, verbose_name=(('Ongoing', 'Ongoing'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')))),
                ('estimated_budget', models.IntegerField()),
                ('total_amount_spent', models.IntegerField()),
                ('project_duration', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('home_mod_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.HomeModificationTask')),
            ],
        ),
    ]
