# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0059_homemodproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemodproject',
            name='project_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='homemodproject',
            name='total_amount_spent',
            field=models.IntegerField(default=0),
        ),
    ]
