# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0060_auto_20181110_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodproject',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client'),
        ),
        migrations.AddField(
            model_name='homemodproject',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.HomeModificationUser'),
        ),
    ]
