# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0061_auto_20181111_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemodproject',
            name='home_mod_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='mycareportal_app.HomeModificationTask'),
        ),
    ]
