# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0063_auto_20181129_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModProjectAmountSpentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_amount_spent', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('home_mod_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.HomeModProject')),
            ],
        ),
        migrations.CreateModel(
            name='HomeModProjectBudgetLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('estimated_budget', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('home_mod_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.HomeModProject')),
            ],
        ),
        migrations.CreateModel(
            name='HomeModProjectDurationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project_duration', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('home_mod_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.HomeModProject')),
            ],
        ),
        migrations.CreateModel(
            name='HomeModProjectProgressLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('home_mod_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.HomeModProject')),
            ],
        ),
        migrations.CreateModel(
            name='HomeModProjectStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10, verbose_name=(('Ongoing', 'Ongoing'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')))),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('home_mod_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.HomeModProject')),
            ],
        ),
    ]
