# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0064_homemodprojectamountspentlog_homemodprojectbudgetlog_homemodprojectdurationlog_homemodprojectprogres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemodprojectamountspentlog',
            name='home_mod_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.HomeModProject'),
        ),
        migrations.AlterField(
            model_name='homemodprojectbudgetlog',
            name='home_mod_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.HomeModProject'),
        ),
        migrations.AlterField(
            model_name='homemodprojectdurationlog',
            name='home_mod_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.HomeModProject'),
        ),
        migrations.AlterField(
            model_name='homemodprojectprogresslog',
            name='home_mod_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.HomeModProject'),
        ),
        migrations.AlterField(
            model_name='homemodprojectstatuslog',
            name='home_mod_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.HomeModProject'),
        ),
    ]
