# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-02 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import mycareportal_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0065_auto_20181130_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='movemanager',
            name='address',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movemanager',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movemanager',
            name='date_of_birth',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movemanager',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movemanager',
            name='gender',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movemanager',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movemanager',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movemanager',
            name='phone_number',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movemanager',
            name='profile_picture',
            field=models.ImageField(default=None, upload_to=mycareportal_app.models.get_move_manager_profile_picture_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movemanager',
            name='state',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movemanager',
            name='zip_code',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
