# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0066_auto_20181202_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveManageTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('new_address_max_distance', models.IntegerField()),
                ('type_of_home', models.CharField(max_length=20, verbose_name=(('HOUSE', 'House'), ('TOWNHOUSE', 'Townhouse'), ('APARTMENT', 'Apartment'), ('SENIORFACILITY', 'Senior Facility')))),
                ('provides_assistance', models.BooleanField()),
                ('minimum_cost', models.IntegerField()),
                ('maximum_cost', models.IntegerField()),
                ('type_of_area', models.CharField(max_length=40, verbose_name=(('CITY', 'City'), ('URBAN', 'Urban'), ('SUBURBAN', 'Suburban'), ('RURAL', 'Rural')))),
                ('handicap_friendly', models.BooleanField()),
                ('furnished', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
    ]
