# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0067_movemanagetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='movemanagetask',
            name='assigned_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_manager', to='mycareportal_app.MoveManager'),
        ),
        migrations.AddField(
            model_name='movemanagetask',
            name='chosen_manager',
            field=models.ManyToManyField(null=True, to='mycareportal_app.MoveManager'),
        ),
        migrations.AddField(
            model_name='movemanagetask',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movemanagetask',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movemanagetask',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
