# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0069_auto_20181204_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveManageTaskInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item', models.CharField(max_length=100)),
                ('item_quantity', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('move_manage_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.MoveManageTask')),
            ],
        ),
    ]
