# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-03 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0071_activationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='movemanagetaskinventory',
            name='item_destination',
            field=models.CharField(blank=True, max_length=10, verbose_name=(('HOME', 'Home'), ('STORE', 'Store'), ('CHARITY', 'Charity'), ('OTHER', 'Other'))),
        ),
        migrations.AddField(
            model_name='movemanagetaskinventory',
            name='item_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movemanagetaskinventory',
            name='item_sale_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='activation_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
    ]
