# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-03 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import mycareportal_app.models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0072_auto_20190203_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='movemanagetaskinventory',
            name='item_image',
            field=models.ImageField(null=True, upload_to=mycareportal_app.models.get_move_inventory_upload_path),
        )
    ]
