# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0073_auto_20190203_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveManageTaskBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cost', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('move_manage_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.MoveManageTask')),
                ('move_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.MoveManager')),
            ],
        )
    ]
