# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-03 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0074_auto_20190203_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcode',
            name='activation_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
    ]
