# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0074_auto_20190209_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveManagementProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(default='Ongoing', max_length=10, verbose_name=(('Ongoing', 'Ongoing'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')))),
                ('estimated_budget', models.IntegerField()),
                ('total_amount_spent', models.IntegerField(default=0)),
                ('project_duration', models.IntegerField(default=0)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
        migrations.AddField(
            model_name='movemanagetask',
            name='chosen_bid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.MoveManageTaskBid'),
        ),
        migrations.AddField(
            model_name='movemanagementproject',
            name='move_manage_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.MoveManageTask'),
        ),
        migrations.AddField(
            model_name='movemanagementproject',
            name='move_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.MoveManager'),
        ),
    ]
