# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-03 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0075_auto_20190203_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcode',
            name='activation_code',
            field=models.CharField(default='CzNXKsyvCG2poSPzGHJsRm', editable=False, max_length=22, unique=True),
        ),
    ]
