# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0075_auto_20190209_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveProjectAmountSpentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_amount_spent', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('move_management_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.MoveManagementProject')),
            ],
        ),
        migrations.CreateModel(
            name='MoveProjectBudgetLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('estimated_budget', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('move_management_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.MoveManagementProject')),
            ],
        ),
        migrations.CreateModel(
            name='MoveProjectDurationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project_duration', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('move_management_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.MoveManagementProject')),
            ],
        ),
        migrations.CreateModel(
            name='MoveProjectProgressLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('move_management_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.MoveManagementProject')),
            ],
        ),
        migrations.CreateModel(
            name='MoveProjectStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10, verbose_name=(('Ongoing', 'Ongoing'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')))),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('move_management_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.MoveManagementProject')),
            ],
        )
    ]
