# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-18 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0076_auto_20190212_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='activation_code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.ActivationCode'),
        ),
    ]
