# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-18 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0077_auto_20190518_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_on_free_trial',
            field=models.BooleanField(default=False),
        ),
    ]
