# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-26 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0078_auto_20190518_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_template', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('template_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTemplateEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('task_template_code', models.CharField(max_length=100)),
                ('task_template_entry_code', models.CharField(max_length=100)),
                ('entry_type', models.CharField(max_length=100, verbose_name=(('TEXT', 'TEXT'), ('CHECK', 'CHECK'), ('RADIO', 'RADIO'), ('NUMBER', 'NUMBER')))),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTemplateEntryInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('entry_value', models.CharField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('task_template_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.TaskTemplateEntry')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTemplateInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('task_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.TaskSchedule')),
                ('task_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.TaskTemplate')),
            ],
        ),
        migrations.AddField(
            model_name='tasktemplateentryinstance',
            name='task_template_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.TaskTemplateInstance'),
        ),
    ]
