# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0079_auto_20190526_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplateentryinstance',
            name='entry_value',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
