# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-16 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0080_auto_20190527_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_dashboard',
            field=models.CharField(default='ADMIN', max_length=100, verbose_name=(('ADMIN', 'ADMIN'), ('CLIENT', 'CLIENT'), ('CAREGIVER', 'CAREGIVER'))),
        )
    ]
