# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-18 23:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0081_auto_20190616_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        )
    ]
