# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-18 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0082_auto_20190618_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='completed_timestamp',
            field=models.DateTimeField(null=True),
        )
    ]
