# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-18 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0083_auto_20190618_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='hourly_rate',
            field=models.IntegerField(default=0),
        )
    ]
