# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-30 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0084_auto_20190618_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        )
    ]
