# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-22 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0085_auto_20190630_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplateSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_template', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('template_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTemplateSubcategoryInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('task_template_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.TaskTemplateInstance')),
                ('task_template_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.TaskTemplateSubcategory')),
            ],
        ),
        migrations.AddField(
            model_name='tasktemplateentry',
            name='task_template_subcategory_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tasktemplateentryinstance',
            name='task_template_subcategory_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.TaskTemplateSubcategoryInstance'),
        ),
    ]
