# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-27 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0086_auto_20190722_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplatesubcategory',
            name='template_subcategory_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        )
    ]
