# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-11 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import mycareportal_app.models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0087_auto_20190727_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(null=True, upload_to=mycareportal_app.models.get_company_logo_upload_path),
        )
    ]
