# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-11 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0088_auto_20190811_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskheader',
            name='alert_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='alert_active',
            field=models.BooleanField(default=False),
        )
    ]
