# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-11 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0089_auto_20190811_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='task_alert_emails',
            field=models.BooleanField(default=True),
        )
    ]
