# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-23 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0090_auto_20190811_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(max_length=10),
        ),
    ]
