# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-23 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0091_auto_20190823_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='state',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='familycontact',
            name='state',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='homemodificationuser',
            name='state',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='movemanager',
            name='state',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='movemanagetask',
            name='state',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='payer',
            name='state',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='state',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
