# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-04 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0093_auto_20190908_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
