# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-06 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0095_auto_20191028_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='attorney_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        )
    ]
