# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-19 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0096_auto_20191106_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='marked_off',
            field=models.BooleanField(default=False),
        )
    ]
