# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-19 05:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0097_auto_20191119_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='marked_off_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='marked_off_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marked_off_user', to=settings.AUTH_USER_MODEL),
        )
    ]
