# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-22 11:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0098_auto_20191119_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverScheduleDashboardSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('open_filter', models.BooleanField(default=False)),
                ('scheduled_filter', models.BooleanField(default=True)),
                ('in_progress_filter', models.BooleanField(default=False)),
                ('completed_filter', models.BooleanField(default=False)),
                ('late_filter', models.BooleanField(default=False)),
                ('missed_filter', models.BooleanField(default=False)),
                ('caregiver_filter', models.ManyToManyField(blank=True, to='mycareportal_app.Caregiver')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        )
    ]
