# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-11 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0099_auto_20200122_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='movemanagetask',
            name='archived',
            field=models.BooleanField(default=False),
        )
    ]
