# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-30 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0103_auto_20200423_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='account_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
