# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-01 12:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0104_auto_20200530_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyClientVitalTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('breathing_issues', models.CharField(blank=True, max_length=1, null=True)),
                ('Cold_or_Cough', models.CharField(blank=True, max_length=1, null=True)),
                ('bad_throat', models.CharField(blank=True, max_length=1, null=True)),
                ('lack_taste_and_smell', models.CharField(blank=True, max_length=1, null=True)),
                ('headache', models.CharField(blank=True, max_length=1, null=True)),
                ('chest_pain', models.CharField(blank=True, max_length=1, null=True)),
                ('weakness', models.CharField(blank=True, max_length=1, null=True)),
                ('fever', models.CharField(blank=True, max_length=1, null=True)),
                ('body_temperature_38_higher', models.CharField(blank=True, max_length=500, null=True)),
                ('blood_oxygen_level_SpO2_95_below', models.CharField(blank=True, max_length=500, null=True)),
                ('heart_rate_bpm_over_100_bpm_under_60_bpm', models.CharField(blank=True, max_length=500, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_sugar_fasting', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_sugar_non_fasting', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='activation_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
    ]
