# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-03 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0105_notify_client_vital_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_caregiver',
            field=models.BooleanField(default=False),
        )
    ]
