# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-07 21:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mycareportal_app.models
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0106_auto_20200603_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attachment', models.FileField(upload_to=mycareportal_app.models.get_caregiver_attachment_upload_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='caregiver',
            name='notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='caregiverattachment',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Caregiver'),
        ),
        migrations.AddField(
            model_name='caregiverattachment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company'),
        ),
        migrations.AddField(
            model_name='caregiverattachment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
