# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-13 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0107_auto_20200607_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_parent',
            field=models.BooleanField(default=False),
        )
    ]
