# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-25 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0108_company_is_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='requires_tablet',
            field=models.BooleanField(default=True),
        ),
    ]
