# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-07 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0109_auto_20200625_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='holiday_hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='holiday_live_in_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='live_in_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='weekend_holiday_live_in_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='weekend_holiday_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='weekend_hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='weekend_live_in_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='holiday_hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='holiday_live_in_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='live_in_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='regular_hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='weekend_holiday_live_in_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='weekend_holiday_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='weekend_hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='weekend_live_in_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=200, null=True),
        ),
        
    ]
