# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-12 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0110_auto_20200807_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
     
    
    ]
