# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-16 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0110_auto_20200716_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcode',
            name='activation_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='holiday_hourly_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='holiday_live_in_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='live_in_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='special_hourly_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='special_live_in_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='weekend_holiday_live_in_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='weekend_holiday_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='weekend_hourly_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='weekend_live_in_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='holiday_hourly_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='holiday_live_in_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='live_in_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='regular_hourly_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='special_hourly_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='special_live_in_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='weekend_holiday_live_in_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='weekend_holiday_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='weekend_hourly_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='weekend_live_in_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, max_length=200, null=True),
        ),
    ]
