# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-16 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0111_auto_20200812_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='live_in_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='live_in_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=200, null=True),
        ),
    ]
