# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-07 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0111_auto_20200812_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverscheduleheader',
            name='task_type',
            field=models.CharField(max_length=100, null=True),
        )
    ]
