# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-12 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0112_auto_20200816_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverscheduleheader',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
