# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-20 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0113_auto_20200912_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=200)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=200)),
                ('invoice_number_string', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('start_date', models.DateField()),
                ('end_Date', models.DateField()),
                ('invoice_notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=10, max_length=200)),
                ('rate_type', models.CharField(choices=[('NORMAL', 'Regular Rate'), ('WEEKEND', 'Weekend Rate'), ('HOLIDAY', 'Holiday Rate'), ('LIVE_IN', 'Live in Rate'), ('WEEKEND_HOLIDAY', 'Weekend and Holiday'), ('WEEKEND_LIVE_IN', 'Weekend and Live In'), ('HOLIDAY_LIVE_IN', 'Holiday and Live In'), ('WEEKEND_HOLIDAY_LIVE_IN', 'Weekend, Holiday and Live In')], max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, max_length=200)),
                ('custom_service_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=200)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, max_length=200)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Caregiver')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('invoice_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.InvoiceHeader')),
            ],
        ),
        migrations.AddField(
            model_name='caregiverscheduleheader',
            name='live_in',
            field=models.BooleanField(default=False),
        ),
    ]
