# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-08 09:16
from __future__ import unicode_literals

from django.db import migrations


def copy_client_address_to_billing_address(apps, schema_editor):
    Client = apps.get_model('mycareportal_app', 'Client')
    for client in Client.objects.all():
        client.billing_address = client.address
        client.billing_city = client.city
        client.billing_state = client.state
        client.billing_zip_code = client.zip_code
        client.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0115_auto_20200927_2228'),
    ]

    operations = [
        migrations.RunPython(copy_client_address_to_billing_address),
    ]
