# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-18 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0116_auto_20201008_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceheader',
            old_name='end_Date',
            new_name='end_date',
        ),
    ]
