# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-08 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0117_auto_20201018_2336'),
    ]

    operations = [
     
    ]
