# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-08 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0118_auto_20201208_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceheader',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
      
        migrations.AlterField(
            model_name='invoiceheader',
            name='invoice_number_string',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
