# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-19 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0119_auto_20201208_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceheader',
            name='cancelled',
            field=models.BooleanField(default=False),
        )
    ]
