# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-04 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0120_auto_20201219_2323'),
    ]

    operations = [
    
        migrations.AddField(
            model_name='invoiceheader',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=200),
        )
    ]
