# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-11 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0121_auto_20210104_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mileage_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=20, null=True),
        ),
   
    ]
