# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-11 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0122_auto_20210111_1900'),
    ]

    operations = [
  
        migrations.AlterField(
            model_name='company',
            name='mileage_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
