# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-16 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0123_auto_20210111_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_types', models.CharField(max_length=300)),
            ],
        )
    
    ]
