# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-03 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0124_auto_20210116_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmClientLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lead_owner', models.CharField(max_length=300)),
                ('lead_first_name', models.CharField(max_length=100)),
                ('lead_last_name', models.CharField(max_length=100)),
                ('lead_date_of_birth', models.DateTimeField(null=True)),
                ('gender', models.CharField(max_length=1)),
                ('lead_email_address', models.CharField(max_length=100, unique=True)),
                ('lead_source', models.CharField(max_length=100)),
                ('lead_contact_number', models.CharField(max_length=40)),
                ('lead_secondary_phone_number', models.CharField(blank=True, max_length=40)),
                ('lead_status', models.CharField(max_length=100)),
                ('lead_address', models.CharField(max_length=400)),
                ('lead_city', models.CharField(max_length=100)),
                ('lead_state', models.CharField(max_length=100)),
                ('lead_zip_code', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CrmNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('crm_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.CrmClientLead')),
            ],
        )
      
    ]
