# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-05-14 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0125_auto_20210203_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodtaskbid',
            name='bid_live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movemanagetaskbid',
            name='bid_live',
            field=models.BooleanField(default=True),
        )
     
    ]
