# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-04-21 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0125_auto_20210203_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=200)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=200)),
                ('payroll_number_string', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('submitted', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=10, max_length=200)),
                ('rate_type', models.CharField(choices=[('NORMAL', 'Regular Rate'), ('WEEKEND', 'Weekend Rate'), ('HOLIDAY', 'Holiday Rate'), ('LIVE_IN', 'Live in Rate'), ('WEEKEND_HOLIDAY', 'Weekend and Holiday'), ('WEEKEND_LIVE_IN', 'Weekend and Live In'), ('HOLIDAY_LIVE_IN', 'Holiday and Live In'), ('WEEKEND_HOLIDAY_LIVE_IN', 'Weekend, Holiday and Live In')], max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, max_length=200)),
                ('custom_service_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=200)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='caregiver',
            name='regular_hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='completed_by_caregiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Caregiver'),
        ),
       
        migrations.AddField(
            model_name='payrolllineitem',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Caregiver'),
        ),
        migrations.AddField(
            model_name='payrolllineitem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company'),
        ),
        migrations.AddField(
            model_name='payrolllineitem',
            name='payroll_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.PayrollHeader'),
        ),
        migrations.AddField(
            model_name='payrollheader',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Caregiver'),
        ),
        migrations.AddField(
            model_name='payrollheader',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company'),
        ),
    ]
