# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-03 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0127_auto_20210421_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorRejectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.HomeModificationUser')),
                ('home_mod_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.HomeModificationTask')),
            ],
        ),
        migrations.CreateModel(
            name='MoveManagerRejectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.Company')),
                ('move_manage_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.MoveManageTask')),
                ('move_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycareportal_app.MoveManager')),
            ],
        ),
   
    ]
