# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-21 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0128_auto_20210603_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodtaskbid',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movemanagetaskbid',
            name='archived',
            field=models.BooleanField(default=False),
        ),
      
    ]
