# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-06 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0129_auto_20210621_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=300)),
            ],
        )
    ]
