# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-08-16 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('mycareportal_app', '0130_auto_20210706_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverattachment',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientattachment',
            name='active_status',
            field=models.BooleanField(default=True),
        )
  
    ]
